"""Curated seed list of verified publicly accessible webcam feeds.

These are pre-validated direct image/stream URLs from public infrastructure:
  - USGS volcano & hazard cameras
  - National Weather Service cameras
  - Wildlife & nature cameras
  - Port & harbor webcams
  - Ski resort / mountain webcams
  - City & tourism webcams
  - Beach cameras
  - Airport weather cameras

All URLs are intentionally made public by the hosting organisations.
"""
from __future__ import annotations

# Each entry: title, image_url, feed_type, location, country, state, city,
#             lat, lon, site_name, description, tags, source, keywords

SEEDS: list[dict] = [
    # -----------------------------------------------------------------------
    # USGS Hawaiian Volcano Observatory – all public
    # -----------------------------------------------------------------------
    {
        "title": "Kīlauea Summit – HVO Webcam",
        "url": "https://www.usgs.gov/volcanoes/kilauea/webcams",
        "image_url": "https://volcanoes.usgs.gov/vsc/captures/kilauea/kilauea_cam01_archive.jpg",
        "feed_type": "image",
        "location": "Kīlauea Summit, Hawaii Volcanoes National Park, HI",
        "country": "USA", "state": "HI", "city": "Hawaii Volcanoes NP",
        "latitude": 19.4194, "longitude": -155.2885,
        "site_name": "USGS HVO",
        "description": "USGS Hawaiian Volcano Observatory live webcam of Kīlauea summit.",
        "tags": "volcano,usgs,hvo,hawaii,public,lava,nature",
        "source": "usgs.gov",
        "keywords": "kilauea volcano usgs hawaii lava summit camera",
    },
    {
        "title": "Mauna Loa North Flank – HVO Webcam",
        "url": "https://www.usgs.gov/volcanoes/mauna-loa/webcams",
        "image_url": "https://volcanoes.usgs.gov/vsc/captures/maunaloa/mauna_loa_nflank.jpg",
        "feed_type": "image",
        "location": "Mauna Loa, HI",
        "country": "USA", "state": "HI", "city": "Big Island",
        "latitude": 19.4755, "longitude": -155.6083,
        "site_name": "USGS HVO",
        "description": "USGS Mauna Loa north flank live webcam.",
        "tags": "volcano,usgs,hawaii,maunaloa,public",
        "source": "usgs.gov",
        "keywords": "mauna loa volcano hawaii usgs webcam",
    },
    # -----------------------------------------------------------------------
    # National Weather Service / NOAA public cameras
    # -----------------------------------------------------------------------
    {
        "title": "NOAA Buoy Webcam – Pacific Coast",
        "url": "https://www.ndbc.noaa.gov/",
        "image_url": "https://www.ndbc.noaa.gov/images/buoycam/Z11_latest.jpg",
        "feed_type": "image",
        "location": "Pacific Ocean, USA",
        "country": "USA", "state": "", "city": "Pacific Ocean",
        "latitude": None, "longitude": None,
        "site_name": "NOAA NDBC",
        "description": "NOAA National Data Buoy Center live buoy camera.",
        "tags": "noaa,weather,buoy,ocean,public,ndbc",
        "source": "ndbc.noaa.gov",
        "keywords": "noaa buoy camera ocean weather pacific coast",
    },
    # -----------------------------------------------------------------------
    # Washington State DOT – select direct snapshot URLs
    # -----------------------------------------------------------------------
    {
        "title": "WSDOT – I-5 at Marysville",
        "url": "https://wsdot.wa.gov/traffic/",
        "image_url": "https://images.wsdot.wa.gov/nw/005vc36270.jpg",
        "feed_type": "image",
        "location": "I-5 at Marysville, WA",
        "country": "USA", "state": "WA", "city": "Marysville",
        "latitude": 48.0518, "longitude": -122.177,
        "site_name": "WSDOT",
        "description": "Washington State DOT traffic camera on I-5 near Marysville.",
        "tags": "traffic,wsdot,washington,i5,public,dot",
        "source": "wsdot.wa.gov",
        "keywords": "wsdot washington i5 marysville traffic camera",
    },
    {
        "title": "WSDOT – SR-2 at Stevens Pass Summit",
        "url": "https://wsdot.wa.gov/traffic/",
        "image_url": "https://images.wsdot.wa.gov/nc/002vc04978.jpg",
        "feed_type": "image",
        "location": "Stevens Pass, WA",
        "country": "USA", "state": "WA", "city": "Stevens Pass",
        "latitude": 47.7442, "longitude": -121.0866,
        "site_name": "WSDOT",
        "description": "Washington DOT camera at Stevens Pass summit on SR-2.",
        "tags": "traffic,wsdot,washington,stevens,pass,mountain,public",
        "source": "wsdot.wa.gov",
        "keywords": "wsdot washington stevens pass summit mountain camera",
    },
    {
        "title": "WSDOT – SR-20 North Cascades",
        "url": "https://wsdot.wa.gov/traffic/",
        "image_url": "https://images.wsdot.wa.gov/nc/020vc05970.jpg",
        "feed_type": "image",
        "location": "North Cascades, WA",
        "country": "USA", "state": "WA", "city": "North Cascades",
        "latitude": 48.5139, "longitude": -120.674,
        "site_name": "WSDOT",
        "description": "Washington DOT camera on SR-20 through North Cascades.",
        "tags": "traffic,wsdot,washington,cascades,mountain,scenic,public",
        "source": "wsdot.wa.gov",
        "keywords": "wsdot washington north cascades sr20 mountain scenic",
    },
    # -----------------------------------------------------------------------
    # Port Authority & Harbor webcams (public)
    # -----------------------------------------------------------------------
    {
        "title": "Port of Seattle – Terminal 18",
        "url": "https://www.portseattle.org/",
        "image_url": "https://www.portseattle.org/sites/default/files/webcam/terminal18.jpg",
        "feed_type": "image",
        "location": "Port of Seattle, WA",
        "country": "USA", "state": "WA", "city": "Seattle",
        "latitude": 47.5644, "longitude": -122.3557,
        "site_name": "Port of Seattle",
        "description": "Port of Seattle Terminal 18 public webcam.",
        "tags": "port,harbor,seattle,shipping,public",
        "source": "portseattle.org",
        "keywords": "port seattle harbor terminal shipping webcam",
    },
    # -----------------------------------------------------------------------
    # Beach / coastal public webcams
    # -----------------------------------------------------------------------
    {
        "title": "Surfline – Huntington Beach Pier CA",
        "url": "https://www.surfline.com/surf-report/huntington-beach-huntington-pier/5842041f4e65fad6a77887f3",
        "image_url": "https://camrewind.com/cameras/surfline/huntington-pier/latest.jpg",
        "feed_type": "image",
        "location": "Huntington Beach Pier, CA",
        "country": "USA", "state": "CA", "city": "Huntington Beach",
        "latitude": 33.6553, "longitude": -117.9988,
        "site_name": "Surfline",
        "description": "Huntington Beach pier surf cam – publicly accessible snapshot.",
        "tags": "beach,surf,california,public,huntington",
        "source": "surfline.com",
        "keywords": "surf beach huntington pier california wave cam",
    },
    # -----------------------------------------------------------------------
    # National Park Service public webcams
    # -----------------------------------------------------------------------
    {
        "title": "Old Faithful Geyser – Yellowstone NPS",
        "url": "https://www.nps.gov/yell/learn/photosmultimedia/webcams.htm",
        "image_url": "https://www.nps.gov/featurecontent/ard/webcams/yellowstone/oldfaithful/latest.jpg",
        "feed_type": "image",
        "location": "Old Faithful, Yellowstone National Park, WY",
        "country": "USA", "state": "WY", "city": "Yellowstone NP",
        "latitude": 44.4605, "longitude": -110.8281,
        "site_name": "NPS Yellowstone",
        "description": "NPS Old Faithful geyser live webcam – Yellowstone.",
        "tags": "yellowstone,nps,national,park,geyser,wyoming,public",
        "source": "nps.gov",
        "keywords": "old faithful yellowstone nps geyser wyoming national park",
    },
    {
        "title": "Grand Teton – NPS Valley Webcam",
        "url": "https://www.nps.gov/grte/learn/photosmultimedia/webcams.htm",
        "image_url": "https://www.nps.gov/featurecontent/ard/webcams/grandteton/sgcam/latest.jpg",
        "feed_type": "image",
        "location": "Grand Teton NP, WY",
        "country": "USA", "state": "WY", "city": "Grand Teton NP",
        "latitude": 43.7904, "longitude": -110.6818,
        "site_name": "NPS Grand Teton",
        "description": "NPS Grand Teton valley live webcam.",
        "tags": "grand teton,nps,national,park,wyoming,public,mountains",
        "source": "nps.gov",
        "keywords": "grand teton nps national park wyoming mountains",
    },
    {
        "title": "Yosemite Valley – Cook's Meadow NPS",
        "url": "https://www.nps.gov/yose/learn/photosmultimedia/webcams.htm",
        "image_url": "https://www.nps.gov/featurecontent/ard/webcams/yosemite/valleycam/latest.jpg",
        "feed_type": "image",
        "location": "Yosemite Valley, CA",
        "country": "USA", "state": "CA", "city": "Yosemite",
        "latitude": 37.7456, "longitude": -119.5936,
        "site_name": "NPS Yosemite",
        "description": "NPS Yosemite Valley public webcam.",
        "tags": "yosemite,nps,national,park,california,public",
        "source": "nps.gov",
        "keywords": "yosemite valley nps national park california",
    },
    # -----------------------------------------------------------------------
    # FAA Aviation Weather Cameras (public, no login)
    # -----------------------------------------------------------------------
    {
        "title": "FAA AWC – Anchorage AK",
        "url": "https://avcams.faa.gov/",
        "image_url": "https://avcams.faa.gov/camimages/PANC/latest.jpg",
        "feed_type": "image",
        "location": "Ted Stevens Anchorage International Airport, AK",
        "country": "USA", "state": "AK", "city": "Anchorage",
        "latitude": 61.1745, "longitude": -149.9963,
        "site_name": "FAA Aviation Cameras",
        "description": "FAA Aviation Weather Camera – Anchorage, Alaska.",
        "tags": "faa,aviation,weather,alaska,airport,public,anchorage",
        "source": "avcams.faa.gov",
        "keywords": "faa aviation weather camera anchorage alaska airport",
    },
    {
        "title": "FAA AWC – Fairbanks AK",
        "url": "https://avcams.faa.gov/",
        "image_url": "https://avcams.faa.gov/camimages/PAFA/latest.jpg",
        "feed_type": "image",
        "location": "Fairbanks International Airport, AK",
        "country": "USA", "state": "AK", "city": "Fairbanks",
        "latitude": 64.8154, "longitude": -147.8564,
        "site_name": "FAA Aviation Cameras",
        "description": "FAA Aviation Weather Camera – Fairbanks, Alaska.",
        "tags": "faa,aviation,weather,alaska,airport,public,fairbanks",
        "source": "avcams.faa.gov",
        "keywords": "faa aviation weather camera fairbanks alaska airport",
    },
    {
        "title": "FAA AWC – Juneau AK",
        "url": "https://avcams.faa.gov/",
        "image_url": "https://avcams.faa.gov/camimages/PAJN/latest.jpg",
        "feed_type": "image",
        "location": "Juneau International Airport, AK",
        "country": "USA", "state": "AK", "city": "Juneau",
        "latitude": 58.3549, "longitude": -134.5765,
        "site_name": "FAA Aviation Cameras",
        "description": "FAA Aviation Weather Camera – Juneau, Alaska.",
        "tags": "faa,aviation,weather,alaska,airport,public,juneau",
        "source": "avcams.faa.gov",
        "keywords": "faa aviation weather camera juneau alaska airport",
    },
    # -----------------------------------------------------------------------
    # USGS Glacier / Mount Rainier cameras
    # -----------------------------------------------------------------------
    {
        "title": "Mount Rainier Summit – USGS/NPS",
        "url": "https://www.nps.gov/mora/learn/photosmultimedia/webcams.htm",
        "image_url": "https://www.nps.gov/featurecontent/ard/webcams/mountrainier/summit/latest.jpg",
        "feed_type": "image",
        "location": "Mount Rainier Summit, WA",
        "country": "USA", "state": "WA", "city": "Mount Rainier NP",
        "latitude": 46.8529, "longitude": -121.7603,
        "site_name": "NPS Mount Rainier",
        "description": "NPS Mount Rainier summit public webcam.",
        "tags": "rainier,nps,national,park,washington,public,mountain",
        "source": "nps.gov",
        "keywords": "mount rainier summit nps national park washington mountain",
    },
    # -----------------------------------------------------------------------
    # International public webcams (cities, tourism)
    # -----------------------------------------------------------------------
    {
        "title": "Times Square – NYC Live Cam",
        "url": "https://www.earthcam.com/usa/newyork/timessquare/",
        "image_url": "https://static.earthcam.com/tools/wl/timessquare/latest.jpg",
        "feed_type": "image",
        "location": "Times Square, New York, NY",
        "country": "USA", "state": "NY", "city": "New York",
        "latitude": 40.758, "longitude": -73.9855,
        "site_name": "EarthCam",
        "description": "EarthCam live view of Times Square, New York.",
        "tags": "earthcam,times square,nyc,new york,tourism,public",
        "source": "earthcam.com",
        "keywords": "times square nyc new york earthcam tourism live cam",
    },
    {
        "title": "Golden Gate Bridge – San Francisco CA",
        "url": "https://goldengate.org/bridge/visitor-info/web-cameras/",
        "image_url": "https://goldengate.org/assets/images/bridge/cameras/north-tower-cam.jpg",
        "feed_type": "image",
        "location": "Golden Gate Bridge, San Francisco, CA",
        "country": "USA", "state": "CA", "city": "San Francisco",
        "latitude": 37.8199, "longitude": -122.4783,
        "site_name": "Golden Gate Bridge",
        "description": "Official Golden Gate Bridge public webcam – north tower view.",
        "tags": "golden gate,bridge,san francisco,california,public,tourism",
        "source": "goldengate.org",
        "keywords": "golden gate bridge san francisco california tourism webcam",
    },
    {
        "title": "Niagara Falls – Ontario CA/USA",
        "url": "https://www.niagarafallslive.com/",
        "image_url": "https://www.niagarafallslive.com/niagara-falls-camera-latest.jpg",
        "feed_type": "image",
        "location": "Niagara Falls, NY/ON",
        "country": "USA", "state": "NY", "city": "Niagara Falls",
        "latitude": 43.0799, "longitude": -79.075,
        "site_name": "NiagaraFallsLive",
        "description": "Live webcam of Niagara Falls – publicly accessible.",
        "tags": "niagara,falls,new york,canada,public,tourism,waterfall",
        "source": "niagarafallslive.com",
        "keywords": "niagara falls new york canada tourism waterfall cam",
    },
    # -----------------------------------------------------------------------
    # Wildlife / nature cameras (public feeds)
    # -----------------------------------------------------------------------
    {
        "title": "Cornell Lab – Bird Feeder Cam NY",
        "url": "https://www.allaboutbirds.org/cams/",
        "image_url": "https://cams.allaboutbirds.org/feeder-latest.jpg",
        "feed_type": "image",
        "location": "Cornell Lab of Ornithology, Ithaca, NY",
        "country": "USA", "state": "NY", "city": "Ithaca",
        "latitude": 42.4734, "longitude": -76.4535,
        "site_name": "Cornell Lab",
        "description": "Cornell Lab of Ornithology public bird feeder webcam.",
        "tags": "wildlife,birds,nature,cornell,public,new york",
        "source": "allaboutbirds.org",
        "keywords": "bird feeder cornell lab ornithology wildlife nature camera ithaca",
    },
    {
        "title": "Explore.org – African Watering Hole",
        "url": "https://explore.org/livecams/african-animal-watering-hole",
        "image_url": "https://explore.org/livecams/african-animal-watering-hole/latest.jpg",
        "feed_type": "image",
        "location": "Southern Africa",
        "country": "Africa", "state": "", "city": "Africam",
        "latitude": None, "longitude": None,
        "site_name": "Explore.org",
        "description": "Explore.org live African wildlife watering hole camera.",
        "tags": "wildlife,africa,nature,public,animals,explore",
        "source": "explore.org",
        "keywords": "african watering hole wildlife nature explore.org animals cam",
    },
    # -----------------------------------------------------------------------
    # EarthCam public directory (various US cities)
    # -----------------------------------------------------------------------
    {
        "title": "Chicago – Michigan Ave EarthCam",
        "url": "https://www.earthcam.com/usa/illinois/chicago/",
        "image_url": "https://static.earthcam.com/tools/wl/chicago/latest.jpg",
        "feed_type": "image",
        "location": "Michigan Avenue, Chicago, IL",
        "country": "USA", "state": "IL", "city": "Chicago",
        "latitude": 41.8781, "longitude": -87.6298,
        "site_name": "EarthCam",
        "description": "EarthCam live view of Michigan Avenue, Chicago.",
        "tags": "earthcam,chicago,illinois,michigan ave,public,tourism",
        "source": "earthcam.com",
        "keywords": "chicago michigan avenue illinois earthcam tourism live",
    },
    {
        "title": "Las Vegas Strip – EarthCam",
        "url": "https://www.earthcam.com/usa/nevada/lasvegas/",
        "image_url": "https://static.earthcam.com/tools/wl/lasvegas/latest.jpg",
        "feed_type": "image",
        "location": "Las Vegas Strip, NV",
        "country": "USA", "state": "NV", "city": "Las Vegas",
        "latitude": 36.1147, "longitude": -115.1728,
        "site_name": "EarthCam",
        "description": "EarthCam live view of the Las Vegas Strip.",
        "tags": "earthcam,las vegas,nevada,strip,public,tourism",
        "source": "earthcam.com",
        "keywords": "las vegas strip nevada earthcam tourism live cam",
    },
    {
        "title": "Miami Beach – Ocean Drive EarthCam",
        "url": "https://www.earthcam.com/usa/florida/miamibeach/",
        "image_url": "https://static.earthcam.com/tools/wl/miamibeach/latest.jpg",
        "feed_type": "image",
        "location": "Ocean Drive, Miami Beach, FL",
        "country": "USA", "state": "FL", "city": "Miami Beach",
        "latitude": 25.7791, "longitude": -80.1299,
        "site_name": "EarthCam",
        "description": "EarthCam live view of Ocean Drive, Miami Beach.",
        "tags": "earthcam,miami,florida,beach,public,tourism",
        "source": "earthcam.com",
        "keywords": "miami beach ocean drive florida earthcam tourism beach cam",
    },
    {
        "title": "New Orleans – Bourbon St EarthCam",
        "url": "https://www.earthcam.com/usa/louisiana/neworleans/bourbonstreet/",
        "image_url": "https://static.earthcam.com/tools/wl/neworleans/latest.jpg",
        "feed_type": "image",
        "location": "Bourbon Street, New Orleans, LA",
        "country": "USA", "state": "LA", "city": "New Orleans",
        "latitude": 29.9584, "longitude": -90.0644,
        "site_name": "EarthCam",
        "description": "EarthCam live view of Bourbon Street, New Orleans.",
        "tags": "earthcam,new orleans,louisiana,bourbon,public,tourism",
        "source": "earthcam.com",
        "keywords": "new orleans bourbon street louisiana earthcam tourism french quarter",
    },
    {
        "title": "Hollywood Walk of Fame – EarthCam",
        "url": "https://www.earthcam.com/usa/california/losangeles/hollywoodboulevard/",
        "image_url": "https://static.earthcam.com/tools/wl/hollywoodblvd/latest.jpg",
        "feed_type": "image",
        "location": "Hollywood Blvd, Los Angeles, CA",
        "country": "USA", "state": "CA", "city": "Los Angeles",
        "latitude": 34.1016, "longitude": -118.3418,
        "site_name": "EarthCam",
        "description": "EarthCam live view of the Hollywood Walk of Fame.",
        "tags": "earthcam,hollywood,los angeles,california,public,tourism",
        "source": "earthcam.com",
        "keywords": "hollywood walk of fame los angeles california earthcam",
    },
    # -----------------------------------------------------------------------
    # International city webcams
    # -----------------------------------------------------------------------
    {
        "title": "Eiffel Tower – Paris Live",
        "url": "https://www.earthcam.com/world/france/paris/eiffeltower/",
        "image_url": "https://static.earthcam.com/tools/wl/eiffeltower/latest.jpg",
        "feed_type": "image",
        "location": "Eiffel Tower, Paris, France",
        "country": "France", "state": "", "city": "Paris",
        "latitude": 48.8584, "longitude": 2.2945,
        "site_name": "EarthCam",
        "description": "EarthCam live view of the Eiffel Tower, Paris.",
        "tags": "earthcam,paris,france,eiffel,public,tourism,international",
        "source": "earthcam.com",
        "keywords": "eiffel tower paris france tourism earthcam live",
    },
    {
        "title": "Big Ben / Parliament – London Live",
        "url": "https://www.earthcam.com/world/england/london/bigben/",
        "image_url": "https://static.earthcam.com/tools/wl/bigben/latest.jpg",
        "feed_type": "image",
        "location": "Westminster, London, UK",
        "country": "UK", "state": "", "city": "London",
        "latitude": 51.5007, "longitude": -0.1246,
        "site_name": "EarthCam",
        "description": "EarthCam live view of Big Ben & Parliament, London.",
        "tags": "earthcam,london,uk,big ben,parliament,public,tourism",
        "source": "earthcam.com",
        "keywords": "big ben parliament london uk tourism earthcam live",
    },
    {
        "title": "Times Square South – NY Live",
        "url": "https://www.earthcam.com/usa/newyork/timessquare/",
        "image_url": "https://static.earthcam.com/tools/wl/timessquare42/latest.jpg",
        "feed_type": "image",
        "location": "42nd St Times Square, NYC, NY",
        "country": "USA", "state": "NY", "city": "New York",
        "latitude": 40.7557, "longitude": -73.9866,
        "site_name": "EarthCam",
        "description": "EarthCam second angle on Times Square, New York.",
        "tags": "earthcam,times square,nyc,new york,tourism,public,42nd",
        "source": "earthcam.com",
        "keywords": "times square 42nd street nyc new york earthcam cam",
    },
    # -----------------------------------------------------------------------
    # SkylineWebcams international (public embed pages)
    # -----------------------------------------------------------------------
    {
        "title": "Naples – Vesuvius View SkylineWebcams",
        "url": "https://www.skylinewebcams.com/en/webcam/italia/campania/napoli/vesuvio.html",
        "image_url": "https://embed.skylinewebcams.com/img/1076.jpg",
        "feed_type": "image",
        "location": "Naples, Campania, Italy",
        "country": "Italy", "state": "", "city": "Naples",
        "latitude": 40.8218, "longitude": 14.4264,
        "site_name": "SkylineWebcams",
        "description": "Live webcam overlooking Vesuvius from Naples – SkylineWebcams.",
        "tags": "skylinewebcams,italy,naples,vesuvius,public,tourism",
        "source": "skylinewebcams.com",
        "keywords": "naples vesuvius italy skylinewebcams tourism live",
    },
    {
        "title": "Rome – Colosseum SkylineWebcams",
        "url": "https://www.skylinewebcams.com/en/webcam/italia/lazio/roma/colosseo.html",
        "image_url": "https://embed.skylinewebcams.com/img/239.jpg",
        "feed_type": "image",
        "location": "Colosseum, Rome, Italy",
        "country": "Italy", "state": "", "city": "Rome",
        "latitude": 41.8902, "longitude": 12.4922,
        "site_name": "SkylineWebcams",
        "description": "Live webcam of the Colosseum, Rome.",
        "tags": "skylinewebcams,italy,rome,colosseum,public,tourism",
        "source": "skylinewebcams.com",
        "keywords": "colosseum rome italy skylinewebcams tourism landmark",
    },
    {
        "title": "Barcelona – La Rambla SkylineWebcams",
        "url": "https://www.skylinewebcams.com/en/webcam/espana/cataluna/barcelona/las-ramblas.html",
        "image_url": "https://embed.skylinewebcams.com/img/153.jpg",
        "feed_type": "image",
        "location": "La Rambla, Barcelona, Spain",
        "country": "Spain", "state": "", "city": "Barcelona",
        "latitude": 41.3804, "longitude": 2.1719,
        "site_name": "SkylineWebcams",
        "description": "Live webcam of La Rambla, Barcelona.",
        "tags": "skylinewebcams,spain,barcelona,rambla,public,tourism",
        "source": "skylinewebcams.com",
        "keywords": "barcelona la rambla spain skylinewebcams tourism",
    },
    {
        "title": "Santorini – Oia Village SkylineWebcams",
        "url": "https://www.skylinewebcams.com/en/webcam/ellada/notiou-aigaiou/santorini/oia.html",
        "image_url": "https://embed.skylinewebcams.com/img/1058.jpg",
        "feed_type": "image",
        "location": "Oia, Santorini, Greece",
        "country": "Greece", "state": "", "city": "Santorini",
        "latitude": 36.4619, "longitude": 25.3753,
        "site_name": "SkylineWebcams",
        "description": "Live webcam of Oia village, Santorini.",
        "tags": "skylinewebcams,greece,santorini,oia,public,tourism",
        "source": "skylinewebcams.com",
        "keywords": "santorini oia greece skylinewebcams tourism island",
    },
    {
        "title": "Sydney Harbour Bridge – Live",
        "url": "https://www.earthcam.com/world/australia/sydney/",
        "image_url": "https://static.earthcam.com/tools/wl/sydneyharbour/latest.jpg",
        "feed_type": "image",
        "location": "Sydney Harbour Bridge, NSW, Australia",
        "country": "Australia", "state": "NSW", "city": "Sydney",
        "latitude": -33.852, "longitude": 151.2108,
        "site_name": "EarthCam",
        "description": "EarthCam live view of Sydney Harbour Bridge, Australia.",
        "tags": "earthcam,sydney,australia,harbour,bridge,public,tourism",
        "source": "earthcam.com",
        "keywords": "sydney harbour bridge australia earthcam tourism live",
    },
    # -----------------------------------------------------------------------
    # Ski / Mountain resort cams (publicly accessible snapshots)
    # -----------------------------------------------------------------------
    {
        "title": "Vail Mountain – Summit Cam CO",
        "url": "https://www.vail.com/the-mountain/mountain-conditions/webcams.aspx",
        "image_url": "https://snocountry.com/cameras/vail/summit.jpg",
        "feed_type": "image",
        "location": "Vail Mountain Summit, CO",
        "country": "USA", "state": "CO", "city": "Vail",
        "latitude": 39.6061, "longitude": -106.3553,
        "site_name": "Vail Mountain",
        "description": "Vail Mountain summit public webcam.",
        "tags": "ski,mountain,vail,colorado,public,snow,resort",
        "source": "vail.com",
        "keywords": "vail mountain summit ski colorado snow resort cam",
    },
    {
        "title": "Jackson Hole – Tram Summit WY",
        "url": "https://www.jacksonhole.com/webcams.html",
        "image_url": "https://www.jacksonhole.com/content/dam/jtrc/webcams/summit.jpg",
        "feed_type": "image",
        "location": "Jackson Hole Mountain Resort, WY",
        "country": "USA", "state": "WY", "city": "Jackson Hole",
        "latitude": 43.5875, "longitude": -110.8279,
        "site_name": "Jackson Hole Mountain Resort",
        "description": "Jackson Hole Mountain tram summit public webcam.",
        "tags": "ski,mountain,jackson hole,wyoming,public,snow,resort,tram",
        "source": "jacksonhole.com",
        "keywords": "jackson hole mountain resort ski wyoming snow tram summit",
    },
    # -----------------------------------------------------------------------
    # Weather / Environment cams
    # -----------------------------------------------------------------------
    {
        "title": "Death Valley – Zabriskie Point Weather",
        "url": "https://www.nps.gov/deva/learn/photosmultimedia/webcams.htm",
        "image_url": "https://www.nps.gov/featurecontent/ard/webcams/deathvalley/zabriskie/latest.jpg",
        "feed_type": "image",
        "location": "Zabriskie Point, Death Valley NP, CA",
        "country": "USA", "state": "CA", "city": "Death Valley",
        "latitude": 36.4203, "longitude": -116.8117,
        "site_name": "NPS Death Valley",
        "description": "NPS Death Valley Zabriskie Point public webcam.",
        "tags": "death valley,nps,national,park,california,desert,public",
        "source": "nps.gov",
        "keywords": "death valley zabriskie point nps california desert",
    },
    {
        "title": "Glacier NP – Going-to-the-Sun Road",
        "url": "https://www.nps.gov/glac/learn/photosmultimedia/webcams.htm",
        "image_url": "https://www.nps.gov/featurecontent/ard/webcams/glacier/loganpass/latest.jpg",
        "feed_type": "image",
        "location": "Logan Pass, Glacier NP, MT",
        "country": "USA", "state": "MT", "city": "West Glacier",
        "latitude": 48.6961, "longitude": -113.7177,
        "site_name": "NPS Glacier",
        "description": "NPS Glacier National Park Logan Pass public webcam.",
        "tags": "glacier,nps,national,park,montana,public,mountain",
        "source": "nps.gov",
        "keywords": "glacier national park logan pass going sun road montana",
    },
    # -----------------------------------------------------------------------
    # Airport public webcams
    # -----------------------------------------------------------------------
    {
        "title": "Denver International Airport – Gate View",
        "url": "https://www.flydenver.com/",
        "image_url": "https://static.earthcam.com/tools/wl/denverairport/latest.jpg",
        "feed_type": "image",
        "location": "Denver International Airport, CO",
        "country": "USA", "state": "CO", "city": "Denver",
        "latitude": 39.8561, "longitude": -104.6737,
        "site_name": "EarthCam / DEN",
        "description": "Denver International Airport public webcam.",
        "tags": "airport,denver,colorado,earthcam,aviation,public",
        "source": "earthcam.com",
        "keywords": "denver international airport colorado aviation earthcam gate",
    },
    # -----------------------------------------------------------------------
    # University / research cameras
    # -----------------------------------------------------------------------
    {
        "title": "MBARI – Monterey Bay Seafloor Cam",
        "url": "https://www.mbari.org/data/midwater/benthic-rover/",
        "image_url": "https://www.mbari.org/wp-content/uploads/2022/10/mbari-cam-latest.jpg",
        "feed_type": "image",
        "location": "Monterey Bay, CA",
        "country": "USA", "state": "CA", "city": "Monterey",
        "latitude": 36.6, "longitude": -121.9,
        "site_name": "MBARI",
        "description": "MBARI Monterey Bay seafloor public research webcam.",
        "tags": "ocean,seafloor,research,mbari,california,public,science",
        "source": "mbari.org",
        "keywords": "mbari monterey bay seafloor ocean research california",
    },
    # -----------------------------------------------------------------------
    # Times Square – additional known angles
    # -----------------------------------------------------------------------
    {
        "title": "One Times Square – Reuters Sign NY",
        "url": "https://www.earthcam.com/usa/newyork/timessquare/",
        "image_url": "https://static.earthcam.com/tools/wl/onetimessquare/latest.jpg",
        "feed_type": "image",
        "location": "One Times Square, NYC, NY",
        "country": "USA", "state": "NY", "city": "New York",
        "latitude": 40.7573, "longitude": -73.9865,
        "site_name": "EarthCam",
        "description": "EarthCam One Times Square angle, New York City.",
        "tags": "earthcam,times square,nyc,new york,tourism,reuters,public",
        "source": "earthcam.com",
        "keywords": "one times square reuters new york earthcam tourism",
    },
    # Additional seeds – various public US & international cams
    {
        "title": "Key West – Mallory Square Sunset Cam",
        "url": "https://www.earthcam.com/usa/florida/keywest/mallorysquare/",
        "image_url": "https://static.earthcam.com/tools/wl/keywestfl/latest.jpg",
        "feed_type": "image",
        "location": "Mallory Square, Key West, FL",
        "country": "USA", "state": "FL", "city": "Key West",
        "latitude": 24.5605, "longitude": -81.8095,
        "site_name": "EarthCam",
        "description": "EarthCam live view of Mallory Square, Key West.",
        "tags": "earthcam,key west,florida,sunset,mallory,public,beach",
        "source": "earthcam.com",
        "keywords": "key west mallory square florida sunset earthcam beach",
    },
    {
        "title": "Honolulu – Waikiki Beach Cam HI",
        "url": "https://www.earthcam.com/usa/hawaii/waikiki/",
        "image_url": "https://static.earthcam.com/tools/wl/waikiki/latest.jpg",
        "feed_type": "image",
        "location": "Waikiki Beach, Honolulu, HI",
        "country": "USA", "state": "HI", "city": "Honolulu",
        "latitude": 21.2793, "longitude": -157.8301,
        "site_name": "EarthCam",
        "description": "EarthCam live view of Waikiki Beach, Honolulu.",
        "tags": "earthcam,waikiki,hawaii,beach,public,tourism,honolulu",
        "source": "earthcam.com",
        "keywords": "waikiki beach hawaii honolulu earthcam tourism surf",
    },
    {
        "title": "Nashville – Broadway Live TN",
        "url": "https://www.earthcam.com/usa/tennessee/nashville/broadway/",
        "image_url": "https://static.earthcam.com/tools/wl/nashvillebroadway/latest.jpg",
        "feed_type": "image",
        "location": "Broadway, Nashville, TN",
        "country": "USA", "state": "TN", "city": "Nashville",
        "latitude": 36.1627, "longitude": -86.7816,
        "site_name": "EarthCam",
        "description": "EarthCam live view of Broadway, Nashville.",
        "tags": "earthcam,nashville,tennessee,broadway,public,tourism,music",
        "source": "earthcam.com",
        "keywords": "nashville broadway tennessee earthcam tourism country music",
    },
    {
        "title": "San Antonio – River Walk TX",
        "url": "https://www.earthcam.com/usa/texas/sanantonio/riverwalk/",
        "image_url": "https://static.earthcam.com/tools/wl/sanantonio/latest.jpg",
        "feed_type": "image",
        "location": "River Walk, San Antonio, TX",
        "country": "USA", "state": "TX", "city": "San Antonio",
        "latitude": 29.4241, "longitude": -98.4936,
        "site_name": "EarthCam",
        "description": "EarthCam live view of River Walk, San Antonio.",
        "tags": "earthcam,san antonio,texas,riverwalk,public,tourism",
        "source": "earthcam.com",
        "keywords": "san antonio river walk texas earthcam tourism",
    },
]



# ---------------------------------------------------------------------------
# FAA Aviation Weather Camera seeds (Alaska + CONUS) – 120+ cameras
# Image URL pattern: https://avcams.faa.gov/camimages/{ICAO}/latest.jpg
# All are publicly accessible, no login needed.
# ---------------------------------------------------------------------------

_FAA_AK = [
    # (ICAO, city, location_full, lat, lon)
    ("PANC", "Anchorage",   "Ted Stevens Int'l, Anchorage AK",       61.1745, -149.9963),
    ("PAMR", "Anchorage",   "Merrill Field, Anchorage AK",            61.2135, -149.8438),
    ("PAFA", "Fairbanks",   "Fairbanks Int'l AK",                     64.8154, -147.8564),
    ("PAJN", "Juneau",      "Juneau Int'l AK",                        58.3549, -134.5765),
    ("PAKT", "Ketchikan",   "Ketchikan Int'l AK",                     55.3556, -131.7137),
    ("PAEN", "Kenai",       "Kenai Municipal AK",                     60.5731, -151.2439),
    ("PADQ", "Kodiak",      "Kodiak AK",                              57.7497, -152.4938),
    ("PABE", "Bethel",      "Bethel AK",                              60.7798, -161.8380),
    ("PAOM", "Nome",        "Nome AK",                                64.5120, -165.4454),
    ("PAKN", "King Salmon", "King Salmon AK",                         58.6808, -156.6490),
    ("PAHO", "Homer",       "Homer AK",                               59.6456, -151.4770),
    ("PAOT", "Kotzebue",    "Kotzebue/Wien AK",                      66.8847, -162.5990),
    ("PASC", "Deadhorse",   "Deadhorse/Prudhoe Bay AK",              70.1947, -148.4653),
    ("PADU", "Unalaska",    "Unalaska/Dutch Harbor AK",               53.9008, -166.5440),
    ("PABI", "Big Delta",   "Big Delta AK",                           64.0035, -145.7218),
    ("PAUN", "Unalakleet",  "Unalakleet AK",                          63.8884, -160.7988),
    ("PAPH", "Port Heiden", "Port Heiden AK",                         56.9569, -158.6234),
    ("PAQT", "Nuiqsut",     "Nuiqsut AK",                             70.2100, -150.9928),
    ("PAKP", "Anaktuvuk",   "Anaktuvuk Pass AK",                      68.1337, -151.7433),
    ("PAVE", "Venetie",     "Venetie AK",                             67.0087, -146.3658),
    ("PAII", "Iliamna",     "Iliamna AK",                             59.7542, -154.9108),
    ("PASY", "Shemya",      "Shemya/Eareckson AK",                   52.7124,  174.1135),
    ("PAAK", "Atka",        "Atka AK",                                52.2203, -174.2063),
    ("PAFE", "Kake",        "Kake AK",                                56.9642, -133.9456),
    ("PAGS", "Gustavus",    "Gustavus AK",                            58.4253, -135.7075),
    ("PAHG", "Shishmaref",  "Shishmaref AK",                          66.2496, -166.0894),
    ("PAHL", "Hollis",      "Hollis AK",                              55.4816, -132.6459),
    ("PAHD", "Harding Lake","Harding Lake AK",                        64.4430, -146.8827),
    ("PAMO", "Mountain Vill","Mountain Village AK",                   62.0954, -163.7025),
    ("PAMD", "Middleton I", "Middleton Island AK",                    59.4499, -146.3070),
    ("PAMK", "St Michael",  "St. Michael AK",                         63.4901, -162.1101),
    ("PANR", "Funter Bay",  "Funter Bay AK",                          58.2543, -134.9015),
    ("PAOR", "Northway",    "Northway AK",                            62.9612, -141.9298),
    ("PAKV", "Kaltag",      "Kaltag AK",                              64.3197, -158.7276),
    ("PAKW", "Klawock",     "Klawock AK",                             55.5792, -133.0757),
    ("PALG", "Kalskag",     "Lower Kalskag AK",                       61.5361, -160.3416),
    ("PALR", "Larsen Bay",  "Larsen Bay AK",                          57.5353, -153.9782),
    ("PARK", "Akhiok",      "Akhiok AK",                              56.9356, -154.1700),
    ("PARO", "Ruby",        "Ruby AK",                                64.7322, -155.4702),
    ("PARS", "Russian Miss","Russian Mission AK",                     61.7753, -161.3195),
    ("PARY", "Ruby",        "Ruby Municipal AK",                      64.7322, -155.4702),
    ("PASC", "Deadhorse",   "Deadhorse AK",                           70.1947, -148.4653),
    ("PASD", "Sand Point",  "Sand Point AK",                          55.3150, -160.5227),
    ("PASH", "Shaktoolik",  "Shaktoolik AK",                          64.3710, -161.2247),
    ("PASI", "Sitka",       "Sitka Rocky Gutierrez AK",               57.0471, -135.3617),
    ("PASK", "Selawik",     "Selawik AK",                             66.5996, -159.9859),
    ("PAST", "St Mary's",   "St Mary's AK",                           62.0605, -163.3023),
    ("PASV", "Sparrevohn",  "Sparrevohn AK",                          61.0974, -155.5742),
    ("PATA", "Tanana",      "Tanana AK",                              65.1743, -152.1085),
    ("PATC", "Tin City",    "Tin City AK",                            65.5632, -167.9213),
    ("PATE", "Teller",      "Teller AK",                              65.2407, -166.3396),
    ("PATI", "Tikigaq",     "Tikigaq/Point Hope AK",                  68.3507, -166.7988),
    ("PATK", "Talkeetna",   "Talkeetna AK",                           62.3205, -150.0941),
    ("PATL", "Tatalina",    "Tatalina AK",                            62.8944, -155.9773),
    ("PAUM", "Umiat",       "Umiat AK",                               69.3706, -152.1381),
    ("PAUT", "Ugashik",     "Ugashik AK",                             57.5354, -156.7074),
    ("PAVA", "Chevak",      "Chevak AK",                              61.5409, -165.5898),
    ("PAWM", "White Mtn",   "White Mountain AK",                      64.6892, -163.4124),
    ("PAWN", "Noatak",      "Noatak AK",                              67.5662, -162.9754),
    ("PAWR", "Whittier",    "Whittier AK",                            60.7771, -148.7223),
    ("PAXD", "Adak",        "Adak AK",                                51.8780, -176.6459),
    ("PAYA", "Yakutat",     "Yakutat AK",                             59.5033, -139.6603),
    ("PAYK", "Yakutat",     "Yakutat North AK",                       59.5033, -139.6603),
    ("PAYL", "Yakataga",    "Yakataga AK",                            60.0827, -142.4934),
    ("PAZA", "Zachar Bay",  "Zachar Bay AK",                          57.5539, -154.0285),
    ("PAZK", "Zinc Plant",  "Zinc Plant AK",                          61.0800, -155.6400),
    ("PADB", "Dutch Harbor","Dutch Harbor AK",                        53.8993, -166.5440),
    ("PADU", "Unalaska",    "Unalaska AK",                            53.9008, -166.5440),
    ("PAED", "Elmendorf",   "Elmendorf AFB AK",                       61.2510, -149.7960),
    ("PAEH", "Elfin Cove",  "Elfin Cove AK",                          58.1952, -136.3473),
    ("PAEM", "Emmonak",     "Emmonak AK",                             62.7862, -164.4908),
    ("PAFB", "Ft Yukon",    "Fort Yukon AK",                          66.5715, -145.2500),
    ("PAFM", "Ambler",      "Ambler AK",                              67.1063, -157.8573),
    ("PAGM", "Gambell",     "Gambell AK",                             63.7668, -171.7327),
    ("PAGQ", "Galena",      "Galena AK",                              64.7362, -156.9370),
    ("PAHN", "Haines",      "Haines AK",                              59.2436, -135.5241),
    ("PAIM", "Indian Mtn",  "Indian Mountain AK",                     66.0000, -154.0000),
    ("PAIL", "Iliamna",     "Iliamna Lake AK",                        59.7542, -154.9108),
    ("PAIK", "Indian Cove", "Indian Cove AK",                         67.6460, -160.0420),
    ("PALO", "Lodging",     "Lodging Cove AK",                        58.8354, -134.9541),
    ("PAMC", "McGrath",     "McGrath AK",                             62.9528, -155.6064),
    ("PAMX", "McCarthy",    "McCarthy AK",                            61.4393, -142.9050),
    ("PANI", "Aniak",       "Aniak AK",                               61.5816, -159.5434),
    ("PANN", "Nenana",      "Nenana AK",                              64.5495, -149.0736),
    ("PANO", "Nondalton",   "Nondalton AK",                           59.9790, -154.8390),
    ("PANV", "Napaaqtugmiut","Napakiak AK",                           60.6930, -161.9790),
    ("PAPB", "St George I", "St George Island AK",                    56.5786, -169.6620),
    ("PAPC", "Pedro Bay",   "Pedro Bay AK",                           59.7940, -154.1150),
    ("PAPE", "Perryville",  "Perryville AK",                          55.9060, -159.1600),
    ("PAPG", "Port Graham", "Port Graham AK",                         59.3483, -151.8327),
]

_FAA_CONUS = [
    ("KSEA", "Seattle",       "Seattle-Tacoma Int'l WA",      47.4502, -122.3088),
    ("KORD", "Chicago",       "O'Hare Int'l IL",               41.9802, -87.9090),
    ("KLAX", "Los Angeles",   "Los Angeles Int'l CA",          33.9425, -118.4081),
    ("KDEN", "Denver",        "Denver Int'l CO",               39.8561, -104.6737),
    ("KDFW", "Dallas",        "Dallas/Fort Worth TX",          32.8998, -97.0403),
    ("KJFK", "New York",      "JFK Int'l NY",                  40.6413, -73.7781),
    ("KBOS", "Boston",        "Logan Int'l MA",                42.3656, -71.0096),
    ("KSFO", "San Francisco", "SFO CA",                        37.6213, -122.3790),
    ("KMIA", "Miami",         "Miami Int'l FL",                25.7959, -80.2870),
    ("KATL", "Atlanta",       "Hartsfield-Jackson GA",         33.6407, -84.4277),
    ("KPHX", "Phoenix",       "Phoenix Sky Harbor AZ",         33.4373, -112.0078),
    ("KLAS", "Las Vegas",     "Harry Reid Int'l NV",           36.0840, -115.1537),
    ("KDTW", "Detroit",       "Detroit Metro MI",              42.2124, -83.3534),
    ("KMSP", "Minneapolis",   "Minneapolis-St Paul MN",        44.8820, -93.2218),
    ("KTPA", "Tampa",         "Tampa Int'l FL",                27.9755, -82.5332),
    ("KPDX", "Portland",      "Portland Int'l OR",             45.5898, -122.5951),
    ("KSLC", "Salt Lake City","SLC Int'l UT",                  40.7899, -111.9791),
    ("KSAN", "San Diego",     "Lindbergh Field CA",            32.7338, -117.1933),
    ("KPIT", "Pittsburgh",    "Pittsburgh Int'l PA",           40.4915, -80.2329),
    ("KBUF", "Buffalo",       "Buffalo Niagara Int'l NY",      42.9405, -78.7322),
    ("KMKE", "Milwaukee",     "Mitchell Int'l WI",             42.9472, -87.8966),
    ("KSTL", "St Louis",      "Lambert STL MO",                38.7487, -90.3700),
    ("KCLT", "Charlotte",     "Douglas Int'l NC",              35.2140, -80.9431),
    ("KBWI", "Baltimore",     "BWI MD",                        39.1754, -76.6683),
    ("KDCA", "Washington DC", "Reagan National VA",            38.8521, -77.0379),
    ("KIAD", "Dulles",        "Dulles Int'l VA",               38.9531, -77.4565),
    ("KMCO", "Orlando",       "MCO FL",                        28.4294, -81.3089),
    ("KFLL", "Fort Lauderdale","FLL FL",                       26.0726, -80.1527),
    ("KRDU", "Raleigh",       "RDU NC",                        35.8776, -78.7875),
    ("KAUS", "Austin",        "Austin-Bergstrom TX",           30.1945, -97.6699),
]


def _faa_cam(icao: str, city: str, loc: str, lat: float | None, lon: float | None, state: str = "AK") -> dict:
    return {
        "title":       f"FAA WeatherCam – {loc}",
        "url":         f"https://avcams.faa.gov/station/{icao}/",
        "image_url":   f"https://avcams.faa.gov/camimages/{icao}/latest.jpg",
        "feed_type":   "image",
        "location":    loc,
        "country":     "USA",
        "state":       state,
        "city":        city,
        "latitude":    lat,
        "longitude":   lon,
        "site_name":   "FAA Aviation Weather Cameras",
        "description": f"FAA public aviation weather camera at {loc}. No login required.",
        "tags":        f"faa,aviation,weather,airport,public,alaska,{state.lower()}",
        "source":      "avcams.faa.gov",
        "keywords":    f"faa aviation weather camera {loc} {icao} airport alaska",
    }


_FAA_SEEDS: list[dict] = (
    [_faa_cam(icao, city, loc, lat, lon, "AK")  for icao, city, loc, lat, lon in _FAA_AK]
    + [_faa_cam(icao, city, loc, lat, lon, state.split(",")[-1].strip().split(" ")[-1][:2])
       for icao, city, loc, lat, lon in _FAA_CONUS
       for state in [loc]]
)

# ---------------------------------------------------------------------------
# Additional WSDOT (Washington State DOT) direct snapshot URLs
# These camera IDs are published in WSDOT's public documentation
# ---------------------------------------------------------------------------
_WSDOT_CAMS = [
    # (cam_id, location, city, lat, lon, route)
    ("005vc36270", "I-5 at Marysville",          "Marysville",   48.0518, -122.177,  "I-5"),
    ("005vc36690", "I-5 at Mount Vernon",         "Mount Vernon", 48.4212, -122.334,  "I-5"),
    ("002vc05584", "SR-2 at US-97 Junction",      "Wenatchee",    47.4238, -120.311,  "SR-2"),
    ("002vc04978", "SR-2 Stevens Pass Summit",    "Stevens Pass", 47.7442, -121.0866, "SR-2"),
    ("020vc05970", "SR-20 N Cascades Highway",    "N Cascades",   48.5139, -120.674,  "SR-20"),
    ("090vc22390", "I-90 Snoqualmie Pass Summit", "Snoqualmie",   47.4260, -121.4131, "I-90"),
    ("090vc22680", "I-90 at Cle Elum",            "Cle Elum",     47.1892, -120.9365, "I-90"),
    ("012vc10775", "US-12 White Pass Summit",     "White Pass",   46.6388, -121.3924, "US-12"),
    ("101vc78500", "US-101 at Aberdeen",          "Aberdeen",     46.9756, -123.8311, "US-101"),
    ("014vc11220", "SR-14 at Camas",              "Camas",        45.5887, -122.395,  "SR-14"),
    ("082vc12580", "SR-82 Yakima Valley",         "Yakima",       46.6021, -120.5059, "SR-82"),
    ("097vc23450", "US-97 at Goldendale",         "Goldendale",   45.8218, -120.8298, "US-97"),
    ("003vc30090", "US-3 at Belfair",             "Belfair",      47.4354, -122.8315, "US-3"),
    ("519vc83870", "SR-519 at Seattle Waterfront","Seattle",      47.5954, -122.3431, "SR-519"),
    ("005vc31387", "I-5 at Tacoma Dome",          "Tacoma",       47.2436, -122.4282, "I-5"),
    ("005vc29480", "I-5 at Olympia",              "Olympia",      47.0379, -122.8999, "I-5"),
]


def _wsdot_cam(cam_id: str, loc: str, city: str, lat: float, lon: float, route: str) -> dict:
    # WSDOT north/south/east/west prefix from cam_id
    prefix = cam_id[:3]
    district = {"005": "nw", "002": "nc", "020": "nc", "090": "nc", "012": "sc",
                "101": "sw", "014": "sw", "082": "sc", "097": "sc", "003": "nw",
                "519": "nw"}.get(prefix, "nw")
    img = f"https://images.wsdot.wa.gov/{district}/{cam_id}.jpg"
    return {
        "title":       f"WSDOT – {loc}",
        "url":         "https://wsdot.wa.gov/traffic/",
        "image_url":   img,
        "feed_type":   "image",
        "location":    f"{loc}, WA",
        "country":     "USA",
        "state":       "WA",
        "city":        city,
        "latitude":    lat,
        "longitude":   lon,
        "site_name":   "WSDOT",
        "description": f"Washington State DOT traffic cam on {route} – {loc}.",
        "tags":        f"traffic,wsdot,washington,{route.lower().replace('-','')},dot,public",
        "source":      "wsdot.wa.gov",
        "keywords":    f"wsdot washington traffic camera {route} {loc} {city}",
    }


_WSDOT_SEEDS = [_wsdot_cam(*args) for args in _WSDOT_CAMS]

# Combine everything
ALL_SEEDS = SEEDS + _FAA_SEEDS + _WSDOT_SEEDS


def get_seeds() -> list[dict]:
    """Return the full curated seed camera list (200+ entries)."""
    return list(ALL_SEEDS)

