org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
STOCKSTREAM_BACKEND_BASE_URL=https://stockstreamportfolio-api.azurewebsites.net/
STOCKSTREAM_ANDROID_CLIENT_ID=f72c0a02-b8d1-4ad2-9827-e56428051861
STOCKSTREAM_TENANT_ID=7fcb095b-344f-4c1e-8e12-bc781eb03e72
STOCKSTREAM_BACKEND_SCOPE=api://d4ba03d1-4866-461e-9ab7-65b5780e69fa/access_as_user
